/**
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Address from './Address';





/**
* The PaymentCustomersDTOContact model module.
* @module model/PaymentCustomersDTOContact
* @version 2.0
*/
export default class PaymentCustomersDTOContact {
    /**
    * Constructs a new <code>PaymentCustomersDTOContact</code>.
    * @alias module:model/PaymentCustomersDTOContact
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PaymentCustomersDTOContact</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentCustomersDTOContact} obj Optional instance to populate.
    * @return {module:model/PaymentCustomersDTOContact} The populated <code>PaymentCustomersDTOContact</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentCustomersDTOContact();

            
            
            

            if (data.hasOwnProperty('forename')) {
                obj['forename'] = ApiClient.convertToType(data['forename'], 'String');
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('companyname')) {
                obj['companyname'] = ApiClient.convertToType(data['companyname'], 'String');
            }
            if (data.hasOwnProperty('salutation')) {
                obj['salutation'] = ApiClient.convertToType(data['salutation'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('mobile')) {
                obj['mobile'] = ApiClient.convertToType(data['mobile'], 'String');
            }
            if (data.hasOwnProperty('dob')) {
                obj['dob'] = ApiClient.convertToType(data['dob'], 'String');
            }
            if (data.hasOwnProperty('picture')) {
                obj['picture'] = ApiClient.convertToType(data['picture'], 'String');
            }
            if (data.hasOwnProperty('url_website')) {
                obj['url_website'] = ApiClient.convertToType(data['url_website'], 'String');
            }
            if (data.hasOwnProperty('birthplace')) {
                obj['birthplace'] = ApiClient.convertToType(data['birthplace'], 'String');
            }
            if (data.hasOwnProperty('nationality')) {
                obj['nationality'] = ApiClient.convertToType(data['nationality'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
        }
        return obj;
    }

    /**
    * Customer forename
    * @member {String} forename
    */
    forename = undefined;
    /**
    * Customer surname
    * @member {String} surname
    */
    surname = undefined;
    /**
    * Customer company name
    * @member {String} companyname
    */
    companyname = undefined;
    /**
    * Customer salutation
    * @member {String} salutation
    */
    salutation = undefined;
    /**
    * Customer gender
    * @member {String} gender
    */
    gender = undefined;
    /**
    * Customer title
    * @member {String} title
    */
    title = undefined;
    /**
    * Customer email
    * @member {String} email
    */
    email = undefined;
    /**
    * Customer phone
    * @member {String} phone
    */
    phone = undefined;
    /**
    * Customer mobile
    * @member {String} mobile
    */
    mobile = undefined;
    /**
    * Date of birth '/^\\d{4}-\\d{2}-\\d{2}(T\\d{2}:\\d{2}:\\d{2}[+-]\\d{2}:\\d{2})?$/i'
    * @member {String} dob
    */
    dob = undefined;
    /**
    * The document id of an user picture (To upload the picture use our document service.)
    * @member {String} picture
    */
    picture = undefined;
    /**
    * URL to customer website
    * @member {String} url_website
    */
    url_website = undefined;
    /**
    * Customer birthplace
    * @member {String} birthplace
    */
    birthplace = undefined;
    /**
    * Customer nationality
    * @member {String} nationality
    */
    nationality = undefined;
    /**
    * Customer address
    * @member {module:model/Address} address
    */
    address = undefined;








}


