/**
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import PaymentCustomersDTOContact from './PaymentCustomersDTOContact';





/**
* The PaymentCustomersDTO model module.
* @module model/PaymentCustomersDTO
* @version 2.0
*/
export default class PaymentCustomersDTO {
    /**
    * Constructs a new <code>PaymentCustomersDTO</code>.
    * @alias module:model/PaymentCustomersDTO
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PaymentCustomersDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentCustomersDTO} obj Optional instance to populate.
    * @return {module:model/PaymentCustomersDTO} The populated <code>PaymentCustomersDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentCustomersDTO();

            
            
            

            if (data.hasOwnProperty('contact')) {
                obj['contact'] = PaymentCustomersDTOContact.constructFromObject(data['contact']);
            }
        }
        return obj;
    }

    /**
    * PaymentCustomersDTO
    * @member {module:model/PaymentCustomersDTOContact} contact
    */
    contact = undefined;








}


