/**
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PaymentContainersDTO from '../model/PaymentContainersDTO';
import PaymentContainersList from '../model/PaymentContainersList';
import PaymentContainersProductModel from '../model/PaymentContainersProductModel';
import ProductExceptionPayload from '../model/ProductExceptionPayload';

/**
* PaymentContainers service.
* @module api/PaymentContainersApi
* @version 2.0
*/
export default class PaymentContainersApi {

    /**
    * Constructs a new PaymentContainersApi. 
    * @alias module:api/PaymentContainersApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * GET Payment/Containers
     * Get a list of payment containers
     * @param {Object} opts Optional parameters
     * @param {Number} opts.count The number of items to return.
     * @param {Number} opts.offset The position within the whole result set to start returning items (First element is at 0).
     * @param {String} opts.fields List of fields to include in the result. Nested properties can be accessed with this notation: prop1.prop2  Example: prop3,prop1.prop2
     * @param {String} opts.q A query string to restrict the returned items to given conditions. The query string must consist of any combination of single expressions in the form property:condition.  *                  A condition may contain:  *                      - wildcard \&quot;*\&quot; for any number of characters  *                      - wildcard \&quot;?\&quot; for one character  *                      - ranges in the form [value TO value]  *  *                  Single expressions may combined by &#39;AND&#39;, &#39;OR&#39;, &#39;NOT&#39; operators and parenthesis &#39;(&#39;, &#39;)&#39; for grouping.  *                  Property names can be nested like \&quot;prop1.prop2\&quot;.  *                  Example: (NOT customer.name:meier*) AND (customer.age:[30 TO 40] OR customer.age:[50 TO 60])  *
     * @param {String} opts.sort String with comma separated pairs of field:order (e.g. contact.surname:asc,contact.comapnyname:desc). Result set will be sorted by included fields, in ascending &#39;asc&#39;, or descending &#39;dsc&#39; order.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaymentContainersList} and HTTP response
     */
    paymentContainersGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
        'count': opts['count'],
        'offset': opts['offset'],
        'fields': opts['fields'],
        'q': opts['q'],
        'sort': opts['sort']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = PaymentContainersList;

      return this.apiClient.callApi(
        'Payment/Containers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * GET Payment/Containers
     * Get a list of payment containers
     * @param {Object} opts Optional parameters
     * @param {Number} opts.count The number of items to return.
     * @param {Number} opts.offset The position within the whole result set to start returning items (First element is at 0).
     * @param {String} opts.fields List of fields to include in the result. Nested properties can be accessed with this notation: prop1.prop2  Example: prop3,prop1.prop2
     * @param {String} opts.q A query string to restrict the returned items to given conditions. The query string must consist of any combination of single expressions in the form property:condition.  *                  A condition may contain:  *                      - wildcard \&quot;*\&quot; for any number of characters  *                      - wildcard \&quot;?\&quot; for one character  *                      - ranges in the form [value TO value]  *  *                  Single expressions may combined by &#39;AND&#39;, &#39;OR&#39;, &#39;NOT&#39; operators and parenthesis &#39;(&#39;, &#39;)&#39; for grouping.  *                  Property names can be nested like \&quot;prop1.prop2\&quot;.  *                  Example: (NOT customer.name:meier*) AND (customer.age:[30 TO 40] OR customer.age:[50 TO 60])  *
     * @param {String} opts.sort String with comma separated pairs of field:order (e.g. contact.surname:asc,contact.comapnyname:desc). Result set will be sorted by included fields, in ascending &#39;asc&#39;, or descending &#39;dsc&#39; order.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaymentContainersList}
     */
    paymentContainersGet(opts) {
      return this.paymentContainersGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * GET Payment/Containers/{id}
     * Get all payment containers
     * @param {String} id Search one by provided id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaymentContainersProductModel} and HTTP response
     */
    paymentContainersGetByIdWithHttpInfo(id) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling paymentContainersGetById");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = PaymentContainersProductModel;

      return this.apiClient.callApi(
        'Payment/Containers/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * GET Payment/Containers/{id}
     * Get all payment containers
     * @param {String} id Search one by provided id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaymentContainersProductModel}
     */
    paymentContainersGetById(id) {
      return this.paymentContainersGetByIdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * DELETE Payment/Containers/{id}/assign/{secondary-id}
     * Removes an existing payment container assignment
     * @param {String} id Payment container id
     * @param {String} secondaryId Id for which container is currently assigned to
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PaymentContainersProductModel>} and HTTP response
     */
    paymentContainersIdAssignSecondaryIdDeleteWithHttpInfo(id, secondaryId) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling paymentContainersIdAssignSecondaryIdDelete");
      }

      // verify the required parameter 'secondaryId' is set
      if (secondaryId === undefined || secondaryId === null) {
        throw new Error("Missing the required parameter 'secondaryId' when calling paymentContainersIdAssignSecondaryIdDelete");
      }


      let pathParams = {
        'id': id,
        'secondary-id': secondaryId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = [PaymentContainersProductModel];

      return this.apiClient.callApi(
        'Payment/Containers/{id}/assign/{secondary-id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * DELETE Payment/Containers/{id}/assign/{secondary-id}
     * Removes an existing payment container assignment
     * @param {String} id Payment container id
     * @param {String} secondaryId Id for which container is currently assigned to
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PaymentContainersProductModel>}
     */
    paymentContainersIdAssignSecondaryIdDelete(id, secondaryId) {
      return this.paymentContainersIdAssignSecondaryIdDeleteWithHttpInfo(id, secondaryId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * POST Payment/Containers/{id}/assign/{secondary-id}
     * Assign an existing payment container to ...
     * @param {String} id Payment container id
     * @param {String} secondaryId Id to which container will be assigned
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaymentContainersProductModel} and HTTP response
     */
    paymentContainersIdAssignSecondaryIdPostWithHttpInfo(id, secondaryId) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling paymentContainersIdAssignSecondaryIdPost");
      }

      // verify the required parameter 'secondaryId' is set
      if (secondaryId === undefined || secondaryId === null) {
        throw new Error("Missing the required parameter 'secondaryId' when calling paymentContainersIdAssignSecondaryIdPost");
      }


      let pathParams = {
        'id': id,
        'secondary-id': secondaryId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = PaymentContainersProductModel;

      return this.apiClient.callApi(
        'Payment/Containers/{id}/assign/{secondary-id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * POST Payment/Containers/{id}/assign/{secondary-id}
     * Assign an existing payment container to ...
     * @param {String} id Payment container id
     * @param {String} secondaryId Id to which container will be assigned
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaymentContainersProductModel}
     */
    paymentContainersIdAssignSecondaryIdPost(id, secondaryId) {
      return this.paymentContainersIdAssignSecondaryIdPostWithHttpInfo(id, secondaryId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * DELETE Payment/Containers/{id}
     * Delete payment container
     * @param {String} id Payment container id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PaymentContainersProductModel>} and HTTP response
     */
    paymentContainersIdDeleteWithHttpInfo(id) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling paymentContainersIdDelete");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = [PaymentContainersProductModel];

      return this.apiClient.callApi(
        'Payment/Containers/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * DELETE Payment/Containers/{id}
     * Delete payment container
     * @param {String} id Payment container id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PaymentContainersProductModel>}
     */
    paymentContainersIdDelete(id) {
      return this.paymentContainersIdDeleteWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * PUT Payment/Containers/{id}
     * Update payment container
     * @param {String} id Payment container id
     * @param {module:model/PaymentContainersDTO} body Payment container properties
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaymentContainersProductModel} and HTTP response
     */
    paymentContainersIdPutWithHttpInfo(id, body) {
      let postBody = body;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling paymentContainersIdPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling paymentContainersIdPut");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = PaymentContainersProductModel;

      return this.apiClient.callApi(
        'Payment/Containers/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * PUT Payment/Containers/{id}
     * Update payment container
     * @param {String} id Payment container id
     * @param {module:model/PaymentContainersDTO} body Payment container properties
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaymentContainersProductModel}
     */
    paymentContainersIdPut(id, body) {
      return this.paymentContainersIdPutWithHttpInfo(id, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * POST Payment/Containers
     * Add new containers
     * @param {module:model/PaymentContainersDTO} body Payment container properties
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaymentContainersProductModel} and HTTP response
     */
    paymentContainersPostWithHttpInfo(body) {
      let postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling paymentContainersPost");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth_token'];
      let contentTypes = [];
      let accepts = [];
      let returnType = PaymentContainersProductModel;

      return this.apiClient.callApi(
        'Payment/Containers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * POST Payment/Containers
     * Add new containers
     * @param {module:model/PaymentContainersDTO} body Payment container properties
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaymentContainersProductModel}
     */
    paymentContainersPost(body) {
      return this.paymentContainersPostWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
